apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: Eks-Cluster-Test
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
    - "https://github.com/MNLOPS/addons-argocd.git"
  destinations:
    - server: https://kubernetes.default.svc
      namespace: kube-system